---
abstract: 'Perl wrapper for the SEOmoz API'
author:
  - 'Adam Taylor <ajct@cpan.org>'
build_requires:
  English: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-SEOmoz
requires:
  Carp: 0
  DateTime: 0
  Digest::SHA: 0
  JSON: 0
  LWP::UserAgent: 0
  Moose: 0
  URI::Escape: 0
  namespace::autoclean: 0
resources:
  repository: git://github.com/adamtaylor/WWW-SEOmoz.git
version: 0.03
